### ISSUE TITLE
Editing ESPHome yaml for setup: Expected a dictionary

### ISSUE THREAD

**Issue by ionultd** [Wumfie/ESPHome-HPMA115S0-Sensor-Component#1]
https://i.imgur.com/hGqJKXe.png

**Comment by tom1422** [comment]
Forgot to say in the setup that this should be under a sensor tag. See below:
```
sensor:
  - platform: hpma115s0_esphome
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      unit_of_measurement: "<2.5µm"
      icon:  "mdi:fan"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      unit_of_measurement: "<10.0µm"
      icon: "mdi:fan"
    update_interval: 5s
```
Also remember to include this near the start of the yaml file:
```
uart:
  id: uart_bus
  tx_pin: 9
  rx_pin: 10
  baud_rate: 9600
```
The tx_pin and rx_pin shown above are for the elektor weather station. If you are not using that please update them accordingly.
Let me know if this works for you.
